<a href="https://colab.research.google.com/github/Indirapriyadarshini/Authorship-Attribution/blob/master/Workshop_December_2020_Intro_to_Python_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=darkgreen>Python</font>
## Dr. Scharff
## References : Dr. Parisi & Dr. Scharff slides

<table>
   <img src="http://webpage.pace.edu/fparisi/STEM-2020/images/Logo.jpg"
             width="800">
</table>

# <font color=darkgreen>Introduction</font>


<table>
    <img src="http://webpage.pace.edu/fparisi/STEM-2020/images/cartoon.jpg"
         width="800"  >
</table>

Source: https://xkcd.com/353/ 
***

# <font color=darkblue>What is Python?</font>
- Python was designed by Guido van Rossum and first released in 1991
- It is named after the British comedy troupe Monty Python's Flying Circus
- It is an interpreted language
- Its design is distinguished by its emphasis on readability, simplicity and explicitness with respect to other languages such as Java
- Libraries enhance the capabilities of Python. They are here to help you, developers, and make it faster to program!
- We will look at the following libraries together: NumPy, pandas, and matplotlib

# <font color=darkblue>Getting Help</font>
#### Python official documentation https://docs.python.org/3/ 

#### StackOverflow https://stackoverflow.com 
***

# <font color=darkblue>Toolbox</font>

* We will use: Google Colab https://colab.research.google.com
<br>

* Other options: 

* You may decide to install Python and some tools locally

  * Python https://www.python.org/downloads <br>
  * Anaconda (or Miniconda) for Jupyter notebooks https://www.anaconda.com/distribution/#download-section <br>
  * Visual studio code with the Python extension <br> https://code.visualstudio.com <br> https://code.visualstudio.com/docs/languages/python <br>
  * SublimeText 
https://www.sublimetext.com <br>
* Packages for Data Science: numpy, pandas, scikit-learn, matplotlib, seaborn <br>
* Other packages: statistics, statsmodel, scipy__

# <font color=darkred>Let’s start coding...</font>

# <font color=darkblue>What is Google Colab?</font>

* Text and code, like an interactive book
* Table of contents
* Connect
* Share
* Comments 

# <font color=darkblue>What is a notebook?</font>

##### This document *is* a notebook!


***

# <font color=darkblue>Comments</font>

- Comments are introduced by # in Python
- Multiple line comments are between triple-quote strings '''
- Comments are important for code evolution and maintenance

In [ ]:
# Comment

# <font color=darkblue>Calculating with Python</font>

In [ ]:
10 * 50

500

In [ ]:
10 * 5 + 3 - 1

52

In [ ]:
(10 * 5) + 3 - 1

52

In [ ]:
10 / 3

3.3333333333333335

In [ ]:
10 // 3 # truncating division

3

In [ ]:
10 % 3 # remainder

1

In [ ]:
2 ** 10 # power

1024

In [ ]:
1.3+5

6.3

# <font color=darkblue>Variables</font>

A variable is a place to save information in a program

In [ ]:
x = 5 # assignment. x contains 5. x is the name of the vraiable. 5 is the content of x

In [ ]:
x + 6

11

In [ ]:
y = 10
print(y)

10


In [ ]:
x + y 

15

In [ ]:
a, b = 3, 5

In [ ]:
a

3

In [ ]:
b

5

In [ ]:
a, b = b, a+1

In [ ]:
a

5

In [ ]:
b

4

# <font color=darkblue>Print Function</font>

In [ ]:
print("Hello World")

Hello World


- `print` is a function<br>with one parameter
- “Hello World” is the argument and it is a string<br>
- We use parentheses when calling a function on specific arguments  

In [ ]:
x = 3
print(x) # prints the value of the variable x

3


# <font color=darkblue>Typing</font>
- In Python, everything is an object
- Python can deduce the type of things. This is called dynamic typing
- 3 is an int
- 3.5 is a float (because there is a .)
- A string is between " "
- A boolean is evaluated to True or False
- The function `type(...)` can be used to determine the type of an expression

In [ ]:
type(3) # int

int

In [ ]:
type("Hello") # str

str

In [ ]:
type(3.4) # float

float

In [ ]:
type(True)

bool

# <font color=darkblue>Boolean</font>

In [ ]:
b1 = True
b2 = False

In [ ]:
b1

True

In [ ]:
# boolean operators: not, or and and

not b1

False

In [ ]:
b1 or b2

True

In [ ]:
b1 and b2

False

In [ ]:
# boolean expressions
a, b = 3, 5

In [ ]:
a == b

False

In [ ]:
a != b

True

In [ ]:
a < b

True

In [ ]:
a <= b

True

# <font color=darkblue>Float or Real Numbers</font>
- A `float` is a floating point decimal number (a real number)

In [ ]:
type(3.14)

float

In [ ]:
# float times int results in a float
3.14 * 2

6.28

#### Look at the following examples

In [ ]:
type(3)

int

In [ ]:
# specifying a decimal point makes the number a float
type(3.)

float

In [ ]:
3.14 / 2.1

1.4952380952380953

In [ ]:
3.14 // 2.1  # modulus division works the same the division on ints but the result is a float

1.0

# <font color=darkblue>Strings</font>
 - Strings are immutable sequences of characters. Identified by single or double quotes

 - What does immutable mean?
 
 - There are many built-in functions on strings

 - https://docs.python.org/3.3/library/stdtypes.html?highlight=split 

In [ ]:
s = 'This is a string'

In [ ]:
s1 = 'A quote " ' # use of quote in a string. You can also use 3 single quotes
print(s1)

A quote " 


In [ ]:
s[0] # string begins at index 0

'T'

In [ ]:
# This is a string
s[1:3] # substring from position 1 to 3-1=2

'hi'

In [ ]:
s[2:] #substring from position 2

'is is a string'

In [ ]:
s[-1] # index from the right side

'g'

In [ ]:
s[-2]

'n'

In [ ]:
text = "This is a string %s" # to create parameterized strings
print(text % 5) # returns This is a string  5 

This is a string 5


In [ ]:
s  + " Another string" # concatenation of strings

'This is a string Another string'

In [ ]:
s * 3 # repeats the string 3 times

'This is a stringThis is a stringThis is a string'

<h2 style="background-color: yellow">Exercise</h2>

How to get ‘ll’ from a string containing ‘Hello’?

In [ ]:
s1 = "Hello"
s1[2:4]

'll'

# <font color=darkblue>String Functions</font>

There are lots of functions on strings

- `str.capitalize()` - Return a copy of the string with its first character capitalized and the rest lowercased<br>

- `str.split([sep[, maxsplit]])` - Return a list of the words in the string, using sep as the delimiter string. If `maxsplit` is given, at most `maxsplit` splits are done (thus, the list will have at most `maxsplit+1` elements). If `maxsplit` is not specified or -1, then there is no limit on the number of splits (all possible splits are made)<br>

- `str.upper()` - Return a copy of the string with all the cased characters converted to uppercase 

- What other functions are there?

https://docs.python.org/3.8/library/stdtypes.html#string-methods

In [ ]:
new_string = "how, are, you"
copy_ns = new_string.capitalize()
print(copy_ns)


How, are, you


In [ ]:
new_string = "how, are, you"
copy_ns_c = new_string.upper()
print(copy_ns_c)

HOW, ARE, YOU


In [ ]:
new_string.split(",") # ['How', ' are', ' you']

['how', ' are', ' you']

In [ ]:
w = s.split(" ")
w

['This', 'is', 'a', 'string']

In [ ]:
w[0]

'This'

In [ ]:
[w[i] for i in (0,3)]

['This', 'string']

In [ ]:
len(s1) # length of s1

10

In [ ]:
s = "This is a sring"

In [ ]:
"T" in s # check if T is in the string

True

In [ ]:
print("s " + s)
r = s.replace("t", "o") # replace method applied on object s
print("r " + r)
print("s " + s)

s This is a string
r This is a soring
s This is a string


# <font color=darkblue>List</font>

* A list is a mutable collection of elements. They do not have to be of the same type
* Identified by square brackets and using commas between elements
* Can have duplicates
* What does mutable mean?

In [ ]:
fruit_list = [ "apple", "orange", "lemon"]
print(fruit_list)
type(fruit_list)

['apple', 'orange', 'lemon']


list

In [ ]:
fruit_list.append("grape")

In [ ]:
print(fruit_list)

['apple', 'orange', 'lemon', 'grape']


In [ ]:
fruit_list[2] # starts at position 0

'lemon'

In [ ]:
fruit_list[-2] # starts from the end 

'lemon'

In [ ]:
# fruit_list[10] # index out of range

In [ ]:
fruit_list[1:2] # list[start:end] provides the items from start through end-1

['orange']

In [ ]:
fruit_list[2:] # elements starting at position 2 to the end

['lemon', 'grape']

In [ ]:
del fruit_list[1] # delete element at position 1

In [ ]:
fruit_list

['apple', 'lemon', 'grape']

In [ ]:
list1 = [1,2,3]

In [ ]:
list2 = [4,5]

In [ ]:
list3 = list1 + list2 # concatenation of lists

In [ ]:
list3

[1, 2, 3, 4, 5]

In [ ]:
list1 * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
my_list = ["apple", 1] # list of elements of different types

In [ ]:
my_list

['apple', 1]

In [ ]:
number_list1 = list(range(1,101)) # list is a constructor. It builds a list with elements from 1 to 100
print(number_list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [ ]:
number_list2 = list(range(3)) # range(3) means from 0 to 2
print(number_list2)

[0, 1, 2]


# <font color=darkblue>List Functions</font>

There are a lot of pre-defined functions on lists

https://docs.python.org/3/tutorial/datastructures.html

- `list.append(x)` - Add an item to the end of the list. Equivalent to a[len(a):] = [x]
- `list.insert(i, x)` - Insert an item at a given position i. The first argument is the index of the element before which to insert, so `a.insert(0, x)` inserts at the front of the list, and `a.insert(len(a), x)` is equivalent to `a.append(x)`
- `list.remove(x)` - Remove the first item from the list whose value is `x`. It is an error if there is no such item.
- `list.count(x)` - Return the number of times `x` appears in the list.
- `list.sort(key=None, reverse=False)` - Sort the items of the list in place
- `list.reverse()` - Reverse the elements of the list in place.
- `list.copy()` - Return a shallow copy of the list. Equivalent to `a[:]`.

***
<h2 style="background-color: yellow; color: darkred;">Exercise</h2>

* Create a list of lists of ints
* Ceate a list of strings
* Construct a list composed of the elements from position 2 to 5 using slicing
***



In [ ]:
# List of lists of ints using range
list_1 = list(range(0,6))
list_2 = list(range(6,8))
list_3 = [list_1, list_2]


In [ ]:
list_3

[[0, 1, 2, 3, 4, 5], [6, 7]]

In [ ]:
animals = ["fish", "cow", "tree"]
animals

['fish', 'cow', 'tree']

In [ ]:
# elements 2 to 5 using slicing
x = list_1[2:6]
x

[2, 3, 4, 5]

# <font color=darkblue>Tuple</font>

* A tuple is a immutable sequence of elements
* Identified by parentheses, but also commas
* What does immutable mean?

In [ ]:
t = (5, "John") 

In [ ]:
t[1]

'John'

In [ ]:
t[1] = 'Jim' # Errors. A tuple is immutable

TypeError: ignored

***
# <font color=darkblue>Dictionary</font>

* A dictionary is a mutable sequence of elements  where each element can be accessed via a key and has a value
* Identified by curly braces. But also , and :
* What does mutable mean?

In [ ]:
sport = {"John" : "Soccer", "Jim" : "Baseball", "Paul" : "Football"}

In [ ]:
print(sport)

{'John': 'Soccer', 'Jim': 'Baseball', 'Paul': 'Football'}


In [ ]:
sport

{'Jim': 'Baseball', 'John': 'Soccer', 'Paul': 'Football'}

In [ ]:
sport["John"]

'Soccer'

In [ ]:
sport["John"] = "Tennis"

In [ ]:
sport

{'Jim': 'Baseball', 'John': 'Tennis', 'Paul': 'Football'}

In [ ]:
del sport["Paul"]

In [ ]:
sport

{'Jim': 'Baseball', 'John': 'Tennis'}

# <font color=darkblue>More Calculations with Python using the math library</font>
https://docs.python.org/3.8/library/math.html 

A library is a body of already written code that can be imported and used by developers. It helps the work of developers

The math library contains the commonly used math functions - from sin, cos to log and exp

In [ ]:
import math 
math.pi

3.141592653589793

In [ ]:
math.cos(0)

1.0

In [ ]:
math.floor(3.4)

3

In [ ]:
math.ceil(3.4)

4

In [ ]:
math.cos(math.pi/2)

6.123233995736766e-17

In [ ]:
math.sin(math.pi/2)

1.0

# <font color=darkblue>Defining a Function</font>
- A function is useful to organize and reuse code 
- Functions are introduced with the **def** keyword
- A function takes 0 or more parameters
- A function can do things or return a result
- A function that returns a result uses the **return** keyword
- BTW What is an *idendation*?
  - Indentation is super important. It is used to delimit blocks and it has a meaning
  - If you do not put indentation, you will get an error message 

In [ ]:
def simpleFunction(): 
  print("I made a function without parameters and without return")

In [ ]:
simpleFunction()

I made a function without parameters and without return


In [ ]:
# square is a function with 1 parameter and return
def square(x):
  return x * x

In [ ]:
square(4)

16

In [ ]:
# This is another way to write square
def square(x):
  y = x * x
  return y

In [ ]:
square(5)

25

***
<h2 style="background-color: yellow; color: darkred;">Exercise</h2>

* Define a function that returns 2^n
***

# <font color=darkblue>If Statements</font>
- `if`, `elif` and `else` are used to write conditionals
- Indentation is used to delimit blocks

In [ ]:
x = -1
if x < 0:
    print ("Negative number")

Negative number


In [ ]:
x = -5 # you can change the value of x to try this out 
if x < 0: # condition is True 
  print ("<0")
else: # condition is False
  print (">= 0")

<0


In [ ]:
if x == 0:
    print("Zero number")
elif x < 0:
    print ("Negative number")
else:
    print ("Positive number")

***
<h2 style="background-color: yellow; color: darkred;">Exercise</h2>

* Define a function that returns the max of 2 ints, and then of 3 ints
***

***
# <font color="darkblue">Solution</font>

***

This is one solution of max3. What is yours?

In [ ]:
def max3(x, y, z):
    max = x
    if y > max:
        max = y    
    if z > max:
        max = z
        if y > z:
            max = y
    print("The max of " + str(x) + ", " + str(y) + ", " + str(z) + " is " + str(max))
    return max

<h2 style="background-color: yellow; color: darkred;">Exercise</h2>

* Define a function that compares the lengths of 2 strings and returns the longest string. If the 2 strings have the same length, return the concatenation of the 2 strings
***

# <font color="darkblue">Loops</font>

* Loops are used to repeat pieces of code
* There are for and while loops
* We use **for** when we know how many times we need to repeat code
* We use **while** to repeat code while a condition stands

In [ ]:
# print Hello World 5 times using range
# range(0,5) -> 0, 1, 2, 3, 4 (5-1)
for x in range(0,5):
    #print(x)
    print("Hello World")

In [ ]:
# print the elements of a list using in
my_list = [10,2,3]
for elt in my_list:
    print(elt)

10
2
3


In [ ]:
# sum of th elements of a list

# review of the notation x = x + ...
x = 0
x = x + 10 # x is 10. new x value = old x value + 10

# sum of the elements of a list
# initialize the sum to 0
sum = 0

# go through the list and add the elt to the sum
# pattern matching
for elt in my_list:
  sum = sum + elt

print(sum)

15


In [ ]:
# print i while the condition is true
i = 1 # initialize i
while i < 6:
  print(i)
  i += 1 # update i. i = i+1

***
# <font color=darkgreen>Arrays, Series, DataFrame</font>
***

# <font color="darkblue">Arrays</font>
- `NumPy` defines _n_-dimensional array objects (`ndarray`) of data of the same type and size
- Arrays allow operations between arrays and scalars 

In [ ]:
# lists are appropriate to create an array
import numpy as np
data = [6, 5, 9, 8]
arr = np.array(data)
arr

array([6, 5, 9, 8])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
# operations on arrays
arr * arr

array([36, 25, 81, 64])

In [ ]:
arr + arr

array([12, 10, 18, 16])

In [ ]:
# operation with scalar
1/arr

array([0.16666667, 0.2       , 0.11111111, 0.125     ])

In [ ]:
arr ** 0.5

array([2.44948974, 2.23606798, 3.        , 2.82842712])

In [ ]:
type(data)

list

In [ ]:
type([data,data])

list

In [ ]:
# 2-dimensional array
arr1 = np.array([data, data])
print(arr1)

[[6 5 9 8]
 [6 5 9 8]]


In [ ]:
arr1.shape

(2, 4)

In [ ]:
#number of rows
nb_rows = arr1.shape[0]
nb_rows

2

In [ ]:
#number of columns
nb_columns = arr1.shape[1]
nb_columns

4

# <font color="darkblue">Series and DataFrame</font>
- Pandas provides two important data structures: Series and DataFrame 


**Series**

- A __Series__ is a one-dimensional labeled array containing data in **values** (of any `numpy` data type) and an associated array of data labels called **index**

In [ ]:
import pandas as pd
# series from a list
s = pd.Series([4, 7, 5])
s

0    4
1    7
2    5
dtype: int64

In [ ]:
# the indices of the series are on the left and the values are on the right
s.index    #RangeIndex(start=0, stop=3, step=1) 

RangeIndex(start=0, stop=3, step=1)

In [ ]:
s.values   #array([4, 7, 5]) 

array([4, 7, 5])

In [ ]:
# Another example
# We can also create a series from a dictionary
dict = {'Ohio' : 100, 'New York' : 5, 'New Jersey' : 50} 
s1 = pd.Series(dict)
s1

Ohio          100
New York        5
New Jersey     50
dtype: int64

In [ ]:
s1.index

Index(['Ohio', 'New York', 'New Jersey'], dtype='object')

In [ ]:
s1.values

array([100,   5,  50])

In [ ]:
# Another example
# We can also create a series from 2 arrays - values and index
# pandas.Series( data, index)
s2 = pd.Series([4,7,8], index=['a', 'b', 'c'])
s2

a    4
b    7
c    8
dtype: int64

In [ ]:
s2.index

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
s2.values

array([4, 7, 8])

__DataFrame__

- A __DataFrame__ is a (2-dimensional) spreadsheet-like data structure containing an ordered collection of columns (with often different value types). It has a row and column index

- The most used pandas object

In [ ]:
data =  {'state' : ['Ohio', 'New York', 'New Jersey'], 'year': [2000, 2001, 2002]}
df = pd.DataFrame(data)
df

state  year
0        Ohio  2000
1    New York  2001
2  New Jersey  2002

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.values

array([['Ohio', 2000],
       ['New York', 2001],
       ['New Jersey', 2002]], dtype=object)

In [ ]:
df.columns

Index(['state', 'year'], dtype='object')

In [ ]:
df.head() # By default 5 first rows

state  year
0        Ohio  2000
1    New York  2001
2  New Jersey  2002

In [ ]:
df.tail() # 5 last rows

state  year
0        Ohio  2000
1    New York  2001
2  New Jersey  2002

In [ ]:
df.shape # number of rows and columns in this order

(3, 2)

In [ ]:
df.iloc[1] # row1

state    New York
year         2001
Name: 1, dtype: object

In [ ]:
df.iloc[1]['state'] # specific element

'New York'

In [ ]:
df.index = ['row1', 'row2', 'row3'] # renaming the index
df

state  year
row1        Ohio  2000
row2    New York  2001
row3  New Jersey  2002

In [ ]:
df.replace(['New York'], ['NY']) #replace a value

state  year
row1        Ohio  2000
row2          NY  2001
row3  New Jersey  2002

In [ ]:
df.columns = ['state', 'newyear'] # renaming the columns
print(df.columns)
print(df)

Index(['state', 'newyear'], dtype='object')
           state  newyear
row1        Ohio     2000
row2    New York     2001
row3  New Jersey     2002


# <font color=darkgreen></font>

<table>
   <img src="http://webpage.pace.edu/fparisi/STEM-2020/images/Logo.jpg"
             width="800">
</table>